### ISSUE TITLE
Error on "run" after inputting out of bounds value to analog channel

### ISSUE THREAD

**Issue by jqi-sr-lab** [JQIamo/SetList#68]
After entering a value that is out of bounds, DAQmx gives the following error when you click to run a new cycle: 

    DAQmx Write (Analog 2D DBL NChan NSamp).vi:7060001<append>
    <B>Task Name: </B>_unnamedTask<1108>
    (code -50103)

The only way to clear seems to be restarting all of labview. Our thought is possibly the NI virtual instrument never got closed properly, and so when it goes to update hardware it thinks it's still in the middle of a cycle...? Unclear though. Just updating hardware with new values or re-opening the setlist VI don't seem to fix the problem.

**Comment by dsbarker** [comment]
For recordkeeping:
This still popped up if you had an error on a second card but the first was still loaded, or more generally, any time LoadHardware failed during or after the load of any NI Card.

It would forget about all current tasks without cleaning up after them, resulting in an error message about an unresolved task or sim. (code -200077 ? -20077 ?).
