### ISSUE TITLE
Slow Table Interface

### ISSUE THREAD

**Issue by ZJ** [JQIamo/SetList#69]
Different from #52 because it doesn't show up immediately after a fresh load of SetList.

Sr show me a slow table, and we fired up the VI profiler and found that most of the time was being spent in the VI that adds to the table history.  They'd built up over 1,000 table history items, so this issue may be resolved by capping the total size of the table history.

**Comment by ZJ** [comment]
By way of update, we've basically given up making it any faster than it is.  This just isn't what LV tables were built for.

**Comment by ZJ** [comment]
Reopening, see previous comment.

**Comment by ZJ** [comment]
As per a discussion with Trey just now, RbYb may have ID'd a specific commit somewhere between 1.4.1 & 1.5.0 that is responsible for their specific slow performance.  Will update here if we know more.

**Comment by rbyblab** [comment]
The slowness of the table increase noticeably in the commit 5375e27 "Basic Integration of GIT with save system"

RbYb is using the commit 9c96701 (7th commit after 1.4.0)

**Comment by ZJ** [comment]
That's surprising, since I'm pretty sure none of the items in that or the intervening commits interface directly with the table, or even run unless you're doing a save/load operation.  I'll look into it some time next week.

@rbyblab, could you do me a favor and check RAM usage for LabView running your standard commit vs. 5375e27?  Mostly I'm curious if I introduced something that is hogging too many system resources.

**Comment by rbyblab** [comment]
@ZJ give me a trick to speed up the table interface by replacing the current table with classic table and go back to modern table again.  This trick is working.  The speed of the table interface drastically improved.  It's even faster than usual speed we experience in older version.

**Comment by ZJ** [comment]
As per group meeting today, @rbyblab has already tested if loading a file with this change retains the speed improvements.  It does, so I'm going to go ahead and close this.

I never thought this would happen.
