### ISSUE TITLE
Load SetList from Image File

### ISSUE THREAD

**Issue by jqi-sr-lab** [JQIamo/SetList#74]
SetList should publish the procedure file to a network shared variable so that it can be saved as a header/footer to image files. This would allow us to load the procedure used to take an image from the image file itself.

DSB

**Comment by ZJ** [comment]
Updated plan, given the Git save system exists:
 - Added a warn-if-unsaved option, so that you're prompted to have a recent save in Git (#85)
 - Send the most-recent-save hash with the rest of the Igor string, this lets you refer back to whatever was saved most recently.
