### ISSUE TITLE
Viewer causing error

### ISSUE THREAD

**Issue by jiraphat2200** [JQIamo/SetList#79]
When viewer is launched.  Setlist cannot parse user functions in the table.

**Comment by ZJ** [comment]
Confirmed by @breschovsky, when the viewer is open the main program has troubles.

**Comment by jiraphat2200** [comment]
I found a work around to this problem.  When this problem occur, you can go to user functions box in Setlist, add a line, and delete the line (do some editing) and click update.  It seems like Viewer accidentally clear user function when it load a procedure.
