### ISSUE TITLE
Add Device dropdown from Staging List no longer works

### ISSUE THREAD

**Issue by npisenti** [JQIamo/SetList#88]
Selecting a device from the "Add Device" dropdown doesn't pop up the new device configuration VI anymore. Honestly, I think we should just ditch this, since you can do it from "Manage Devices" anyways.

Thoughts?

**Comment by ZJ** [comment]
Reopening for opinions on removing the dropdown altogether.

**Comment by ZJ** [comment]
My personal opinion is to get rid of it, because it is a rarely used button (how often are you adding a new device) that is taking up space.
