### ISSUE TITLE
Adding a "Collect Data" required override VI to Device class

### ISSUE THREAD

**Issue by ZJ** [JQIamo/SetList#98]
@JQIamo/setlist-admins 

This means touching every device class, so I want to make sure it is a good idea before doing it.

Currently our programming/resetting sequence for a single cycle is something like this:
Parse Table->Request Triggers->Prune HWI->Build HWI->Load->Start->Wait for Done->Clear HW

I'd like to add a phase between the last two stages, so it would look like:
...->Wait for Done->Collect Data->Clear HW

This would allow moving the Analog Input function of the NI card to a place you'd actually think to look for it.  It also makes it possible to make sure all data is collected before CycleDone is issued.

Feedback appreciated, otherwise I'll probably just do it tomorrow.

**Comment by dsbarker** [comment]
This seems like a good idea since we could also use this to ensure cameras
are finishing acquisition correctly.

On Thu, May 19, 2016 at 1:30 PM, Z. Smith <notifications@github.com> wrote:

> @JQIamo/setlist-admins
> <https://github.com/orgs/JQIamo/teams/setlist-admins>
>
> This means touching every device class, so I want to make sure it is a
> good idea before doing it.
>
> Currently our programming/resetting sequence for a single cycle is
> something like this:
> Parse Table->Request Triggers->Prune HWI->Build HWI->Load->Start->Wait for
> Done->Clear HW
>
> I'd like to add a phase between the last two stages, so it would look like:
> ...->Wait for Done->Collect Data->Clear HW
>
> This would allow moving the Analog Input function of the NI card to a
> place you'd actually think to look for it. It also makes it possible to
> make sure all data is collected before CycleDone is issued.
>
> Feedback appreciated, otherwise I'll probably just do it tomorrow.
>
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JQIamo/SetList/issues/98>
>



-- 
Joint Quantum Institute
University of Maryland
4296 Stadium Drive
College Park, MD 20742
Lab: 4254 Stadium Drive, Room 2224
301-405-4090
Office: 4254 Stadium Drive, Room 2263
301-405-1438

**Comment by ZJ** [comment]
I'm waiting to test until after DAMOP, but otherwise this is done.
